project_id = "fbujndjmainizgmligxt"

[functions.send-email]
verify_jwt = false

[functions.monthly-report]
verify_jwt = false

[functions.automation-inactive-clients]
verify_jwt = false

[functions.automation-cashback-available]
verify_jwt = false

[functions.automation-monthly-report]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

[functions.apply-pending-plans]
verify_jwt = false

[functions.automations-api]
verify_jwt = false
