-- Force the official commercial catalog to the current model.
-- This is intentionally explicit so environments with older plan flags are corrected.

ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS slug text UNIQUE,
  ADD COLUMN IF NOT EXISTS badge text,
  ADD COLUMN IF NOT EXISTS marketplace_priority smallint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stripe_product_id text,
  ADD COLUMN IF NOT EXISTS stripe_monthly_price_id text,
  ADD COLUMN IF NOT EXISTS stripe_yearly_price_id text,
  ADD COLUMN IF NOT EXISTS paddle_product_id text,
  ADD COLUMN IF NOT EXISTS paddle_monthly_price_id text,
  ADD COLUMN IF NOT EXISTS paddle_yearly_price_id text,
  ADD COLUMN IF NOT EXISTS cashback boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS loyalty boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS open_agenda boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS automation boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS monthly_reports boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS advanced_reports boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS whatsapp_default boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS premium_templates boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS custom_domain boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS custom_colors boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS support_priority boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS multi_location_ready boolean NOT NULL DEFAULT false;

-- Disable all plans that are not in our list
UPDATE public.plans SET active = false WHERE slug NOT IN ('solo', 'studio', 'elite', 'black') OR slug IS NULL;

INSERT INTO public.plans (
  slug, name, badge, monthly_price, yearly_price, yearly_discount, members_limit, active, sort_order, marketplace_priority,
  paddle_product_id, paddle_monthly_price_id, paddle_yearly_price_id,
  stripe_product_id, stripe_monthly_price_id, stripe_yearly_price_id,
  automatic_messages, open_scheduling, promotions, discount_coupons, whitelabel,
  feature_requests, feature_financial_level, custom_branding,
  cashback, loyalty, open_agenda, automation, monthly_reports, advanced_reports,
  whatsapp_default, premium_templates, custom_domain, custom_colors, support_priority, multi_location_ready
) VALUES
  ('solo', 'Solo', NULL, 49.90, 499.00, 16.69, 1, true, 1, 1,
   'plan_solo', 'plan_solo_monthly', 'plan_solo_yearly',
   'plan_solo', 'plan_solo_monthly', 'plan_solo_yearly',
   true, true, true, true, true,
   true, 'full', true,
   true, true, true, true, true, true,
   true, true, true, true, true, true),
  ('studio', 'Studio', 'MAIS VENDIDO', 69.90, 699.00, 16.69, 3, true, 2, 1,
   'plan_studio', 'plan_studio_monthly', 'plan_studio_yearly',
   'plan_studio', 'plan_studio_monthly', 'plan_studio_yearly',
   true, true, true, true, true,
   true, 'full', true,
   true, true, true, true, true, true,
   true, true, true, true, true, true),
  ('elite', 'Elite', 'PREMIUM', 89.90, 899.00, 16.59, 0, true, 3, 1,
   'plan_elite', 'plan_elite_monthly', 'plan_elite_yearly',
   'plan_elite', 'plan_elite_monthly', 'plan_elite_yearly',
   true, true, true, true, true,
   true, 'full', true,
   true, true, true, true, true, true,
   true, true, true, true, true, true),
  ('black', 'Black', 'MARKETPLACE', 104.90, 1049.00, 16.66, 0, true, 4, 2,
   'plan_black', 'plan_black_monthly', 'plan_black_yearly',
   'plan_black', 'plan_black_monthly', 'plan_black_yearly',
   true, true, true, true, true,
   true, 'full', true,
   true, true, true, true, true, true,
   true, true, true, true, true, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  badge = EXCLUDED.badge,
  monthly_price = EXCLUDED.monthly_price,
  yearly_price = EXCLUDED.yearly_price,
  yearly_discount = EXCLUDED.yearly_discount,
  members_limit = EXCLUDED.members_limit,
  active = true,
  sort_order = EXCLUDED.sort_order,
  marketplace_priority = EXCLUDED.marketplace_priority,
  paddle_product_id = EXCLUDED.paddle_product_id,
  paddle_monthly_price_id = EXCLUDED.paddle_monthly_price_id,
  paddle_yearly_price_id = EXCLUDED.paddle_yearly_price_id,
  stripe_product_id = COALESCE(public.plans.stripe_product_id, EXCLUDED.stripe_product_id),
  stripe_monthly_price_id = COALESCE(public.plans.stripe_monthly_price_id, EXCLUDED.stripe_monthly_price_id),
  stripe_yearly_price_id = COALESCE(public.plans.stripe_yearly_price_id, EXCLUDED.stripe_yearly_price_id),
  automatic_messages = true,
  open_scheduling = true,
  promotions = true,
  discount_coupons = true,
  whitelabel = true,
  feature_requests = true,
  feature_financial_level = 'full',
  custom_branding = true,
  cashback = true,
  loyalty = true,
  open_agenda = true,
  automation = true,
  monthly_reports = true,
  advanced_reports = true,
  whatsapp_default = true,
  premium_templates = true,
  custom_domain = true,
  custom_colors = true,
  support_priority = true,
  multi_location_ready = true,
  updated_at = now();
